### ISSUE TITLE
cannot retrieve economic data with get function

### ISSUE THREAD

**Issue by stnatter** [nhedlund/intrinio#4]
I am trying to get historical data for $VXTYN using:
df = intrinio.get(identifier='$VXTYN', start_date='2016-01-01')
TypeError: get() missing 1 required positional argument: 'endpoint'
not sure what argument is required. can you please help me out?

**Comment by nhedlund** [comment]
The first parameter to get() is the endpoint. This is the kind of data you are requesting, for example prices.

I think you should use:
df = intrinio.get('prices', identifier='$VXTYN', start_date='2016-01-01')

See: https://github.com/nhedlund/intrinio#low-level-functions

**Comment by stnatter** [comment]
using 'prices' i get an empty df. I thought i need to use what Intrinio calls Data Tags
http://docs.intrinio.com/tags/economic#economic-data
which would mean I need to use 'level' but that produces an error:
HTTPError: 404 Client Error: Not Found for url: https://api.intrinio.com/change?identifier=%24VXTYN&start_date=2016-01-01&page_number=1&page_size=250
This API call does what i need:
https://api.intrinio.com/historical_data.csv?identifier=$VXTYN&item=level

Seems your code cannot handle this request. Would be fantastic if you could add the ability to get economic and historical data.

**Comment by nhedlund** [comment]
Then you need to change the endpoint to historical_data and it should work:

df = intrinio.get('historical_data', identifier='$VXTYN', item='level')

**Comment by stnatter** [comment]
that works indeed. thanks so much!
