### ISSUE TITLE
How to retrieve financials

### ISSUE THREAD

**Issue by CharlesFr** [nhedlund/intrinio#5]
How can I retrieve fundamentals using this package?

Such as price to earnings ratio.

**Comment by siuyiuyeung** [comment]
it seems that it doesn't provide such data feeding yet

**Comment by nhedlund** [comment]
Is yearly standardized financials of interest? They include for example price to earnings ratio. I can probably add that feature later today.

![fundamentals](https://user-images.githubusercontent.com/2885358/30580366-85fd09f8-9d1c-11e7-88ae-89e51e984fd8.png)

**Comment by nhedlund** [comment]
This is now implemented in version 0.1.17, use this function to get pricetoearnings (PE ratio) among other fundamental data for Apple for example:

`intrinio.financials('AAPL')`

Other kind of fundamentals are supported too, see the documentation.
