### ISSUE TITLE
Add optional configuration that returns just JSON and not pandas?

### ISSUE THREAD

**Issue by rszemplinski** [nhedlund/intrinio#6]
I was wanting to use this package but saw that the data return type is this panda dataframe stuff which I have never used (or want to learn). I was hoping that you could add some optional configuration which just returns raw json?

Thanks!

**Comment by nhedlund** [comment]
I don't think that is necessary, Pandas has a lot of converters built in including a converter to JSON.
For every function that returns a Pandas DataFrame just add .to_json() at the end to get JSON.

Example:
intrinio.prices('SPY').to_json()

**Comment by rszemplinski** [comment]
Ahh, that's pretty neat! I had no idea that Pandas offered that function. Thanks!
