### ISSUE TITLE
KeyError: 'total_pages'

### ISSUE THREAD

**Issue by demonno** [nhedlund/intrinio#9]
When making a call like this to intrinio API
 
    https://api.intrinio.com/data_point?identifier=AERI&item=marketcap,enterprisevalue,ask_price

Note response does not have `total_pages` at all

```json
{  
   "data":[  
      {  
         "identifier":"AERI",
         "item":"marketcap",
         "value":2053125654.3
      },
      {  
         "identifier":"AERI",
         "item":"enterprisevalue",
         "value":1894659654.3
      },
      {  
         "identifier":"AERI",
         "item":"ask_price",
         "value":57.0
      }
   ],
   "result_count":3,
   "api_call_credits":3
}
```

When using library like this:

     intrinio.get('data_point', identifier='AERI', item='=marketcap,enterprisevalue,ask_price')

this line raises an error: `KeyError: 'total_pages'`

https://github.com/nhedlund/intrinio/blob/3d81044759378f8897742ab10161d14340c31fe2/intrinio/client.py#L75

Suggestion: using default value `1` should solve the issue in such cases:

```python
page.total_pages = response.get('total_pages', 1)
```

**Comment by nhedlund** [comment]
Great bug report!

This is now fixed in version 0.2.0.
